### ISSUE TITLE
What is the specification for the training data?

### ISSUE THREAD

**Issue by kevinlinxc** [hsouri/Cirlcle-Detection-CNN#3]
I want to make my own data set to train this model, how does it need to be formatted in the csv file?

Also, I believe you spelled Circle wrong

**Comment by hsouri** [comment]
Thanks for bringing that to my attention. To create your own dataset you should run dataset.py. You can set trainset size and level of noise [here](https://github.com/hsouri/Cirlcle-Detection-CNN/blob/master/dataset.py#L32).
